# Generated by Django 4.2.3 on 2023-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mmrrmma', '0003_mmrrmma_image_mmrrmma_user_alter_mmrrmma_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmrrmma',
            name='image',
            field=models.ImageField(upload_to='mmrrmmas/', verbose_name='изображение'),
        ),
    ]
